### ISSUE TITLE
feedback on patient onboarding document

### ISSUE THREAD

**Issue by isaacvetter** [smart-on-fhir/health-cards#125]
Aggregated feedback suggestions on the [patient onboarding document](https://github.com/smart-on-fhir/health-cards/blob/main/FAQ/patient-onboarding.md):

- The 'Where do I get..' section feels light - I expect this to be the primary question for people seeking this content. Understanding that each Issuer will have their own SOPs/technology, can this section offer examples that provide a reference point? (e.g. I already got my vaccine and have a paper card).
  - perhaps we at least note that health systems and state immunization registries may be able to issue Health Cards after the fact.
- I think there is value in including the human readable presented form in this document - using something similar to [reference design](https://github.com/smart-on-fhir/health-cards-designs).
- The document mentions destroying a paper-based SHC as a value-add in two places - is it clear to the consumer that re-issue and re-print workflows will exist?
- Sharing the SHC with other apps feels ambiguous in this document. Are we talking about one app to retrieve the SHC and another to hold it? Or is this in reference to a workflow where the SHC is 'uploaded' to a Verifier's app (e.g. flight check-in?).
- Privacy protection is another area I expect to be a focus for already interested individuals. I'd like to see this addressed earlier in the document.

and:
-  how this will work for parents and kids. I assume the parents would just carry the kids' health card in their "wallet" (digital or printed QR), but it might be worth adding this to the FAQ if it's not already in there.

**Comment by isaacvetter** [comment]
>Sharing the SHC with other apps feels ambiguous in this document. Are we talking about one app to retrieve the SHC and another to hold it? Or is this in reference to a workflow where the SHC is 'uploaded' to a Verifier's app (e.g. flight check-in?).

Here's our content:
>>You might also have access to your SMART Health Card barcodes through a website or an app on your phone. You can choose to print these barcodes yourself or let someone scan the barcode right from your personal device. By allowing a person to scan your barcode, you are sharing information about you and your COVID-19 status.
>>
>>You might be able to export your SMART Health Card from one app on your smartphone to another. By exporting or sharing your SMART Health Card with other apps on your phone, you're sharing information about you and your COVID-19 status with those apps.

Yeah, indeed. I was trying to generically cover all the possible workflows:
- sharing from the issuer to a health wallet, 
- sharing from the health wallet to a pass app 
- sharing from the health wallet to a verifier

And once you've got multiple health wallets on your phone, and probably most pass apps will also act as wallets. I don't think a consumer needs to understand these roles, rather it's important that they make an informed decision about what they're sharing and with whom at the point of decision.

**Comment by jstclair2019** [comment]
> > Sharing the SHC with other apps feels ambiguous in this document. Are we talking about one app to retrieve the SHC and another to hold it? Or is this in reference to a workflow where the SHC is 'uploaded' to a Verifier's app (e.g. flight check-in?).

- Sharing the SHC for a verifier's app must be considered in the context of a verifiable presentation (i.e. "yes/no, green check/red X") with some privacy-preserving/selective disclosure mechanism. The airline will not want to see your health data nor hold your FHIR immunization information. 

>> I don't think a consumer needs to understand these roles, rather it's important that they make an informed decision about what they're sharing and with whom at the point of decision.

- The consumer should not be expected to apply a decision-making process for "X credential needed for Y flight to Z location". 

>> By exporting or sharing your SMART Health Card with other apps on your phone, you're sharing information about you and your COVID-19 status with those apps.

- How is the consumer given the opportunity to know what they're sharing and how to selectively disclose it? Is it an opt-in/opt-out model for all data or only "I have my 2nd vaccine last tuesday"? 

>> Privacy protection is another area I expect to be a focus for already interested individuals. I'd like to see this addressed earlier in the document.

- I ack you have a commit to move it up further in the doc, but there was extensive discussion (issue #63 I think) that the credential is a non-W3C credential format without selective disclosure, and I'd offer that merits plain-language description as well.
