### ISSUE TITLE
examples of VCs missing issue and exp dates

### ISSUE THREAD

**Issue by fhirfly** [smart-on-fhir/health-cards#127]
The verifiable credentials spec has these two fields:  

"issuanceDate": 
"expirationDate"

are we not using them?

**Comment by jmandel** [comment]
`issuanceDate` in the VC data model is what's captured in our `nbf` field ("not before" claim, described in the JWT mapping section of the VC data model). `expirationDate` is an optional element of the VC data model that only applies when a credential needs to prospectively expire; the clinical results described in a SMART Health Card do not prospectively expire.

**Comment by DrHouston** [comment]
FYI here is my medical degree - there is an issue date but no expiration date on this, and there cant be - its permanant
[Medical Degree.pdf](https://github.com/smart-on-fhir/health-cards/files/6778519/Medical.Degree.pdf)
