### ISSUE TITLE
"zip" is not a defined header for JWS

### ISSUE THREAD

**Issue by vsmahesh** [smart-on-fhir/health-cards#128]
The documentation (https://smarthealth.cards/#health-cards-are-small) suggests to include `zip: "DEF"` in the header and to compress the payload. `zip` is not defined in the [JWS](https://tools.ietf.org/html/rfc7515), but in [JWE](https://tools.ietf.org/html/rfc7516#section-4.1.3). Are we mixing the two to make the payloads small?

When I got [the example payload](https://smarthealth.cards/examples/example-00-d-jws.txt), the first thing I tried was to see what is in the token using [this online tool ](https://jwt.io/#debugger-io), but in vain. May be the tool is not expecting the `zip` header for a JWS as it is not defined in the specifications.

See a similar discussion here - https://github.com/dvsekhvalnov/jose2go/issues/25#issuecomment-539958151

**Comment by jmandel** [comment]
Thanks for this submission! Some background to begin:

1. JWS Payloads are "an arbitrary sequence of octets." Said another way, "The JWS cryptographic mechanisms provide integrity protection for an arbitrary sequence of octets." (Source: https://tools.ietf.org/html/rfc7515)

2. A JWS Header can contain any number of public or private header fields. The `zip: "DEF"` header is a [standardized public header in the context of JWEs](https://www.iana.org/assignments/jose/jose.xhtml), and can be used as a private header in a JWS.

Essentially JWS supports arbitrary payloads and arbitrary headers. Indeed, we could omit the explicit `zip` header altogether and just write in our spec that DEFLATE compression is always (implicitly) applied; so consider the header a hint/reminder if that helps.

The https://jwt.io tool you linked to is very helpful for inspecting JWTs, but it won't be as useful for looking at the binary payload of non-JWT JWSs like a SMART Health Card. You may still find it helpful for inspecting the header. We'll share additional debugging tools as they're available, so keep an eye on https://smarthealth.cards/#what-testing-tools-are-available-to-validate-smart-health-cards-implementations .

With this context, are you still running into a practical implementation issue? We have examples of successful implementations in Java and can point you to libraries and reference code if that's helpful.

**Comment by vsmahesh** [comment]
Thanks for the clarification @jmandel.

**Comment by deftdawg** [comment]
> With this context, are you still running into a practical implementation issue? We have examples of successful implementations in Java and can point you to libraries and reference code if that's helpful.

If anyone could point me at an java implementation that can deflate properly ootb, I'd be super appreciative ...  

Just spent a couple of hours banging my head off of io.jasonwebtoken which is adding a couple of bytes of header and footer to the payload, such that file detects it as "zlib compressed data"...  This results in the token being unusable by all the verification tools 😭 

```java
            String jws = Jwts.builder()
                .setHeaderParam("kid", jwk.getKeyID())
                .setPayload(jo.toString())
                .compressWith(CompressionCodecs.DEFLATE) // <- this is adding extra header/footer making incompatible output 
                .signWith(
                    SignatureAlgorithm.ES256,
                    privateKey
                ).compact();
```

**Comment by deftdawg** [comment]
To follow up with this, must use nimbus-jose-jwt for Java with the DeflateUtils.compress on the payload... 

**DON'T USE jjwts!** it's implementation of `.compressWith(CompressionCodecs.DEFLATE)` is broken, it does not produce rawDeflate (not can it be configured to do so)!
