### ISSUE TITLE
Clarify multi-JWS treatment in QR codes

### ISSUE THREAD

**Issue by christianpaquin** [smart-on-fhir/health-cards#132]
The spec allows for a `.smart-health-card` file to contain multiple JWS in the `verifiableCredential` property (as specified in the [via File Download](https://smarthealth.cards/#via-file-download) section).

What is the intent for QR codes? The [Every Health Card can be embedded in a QR Code](https://smarthealth.cards/#every-health-card-can-be-embedded-in-a-qr-code) section says:
> the same JWS strings that appear as .verifiableCredential[] entries in a .smart-health-card file SHALL be encoded as Numerical Mode QR codes consisting of the digits 0-9  (see "Encoding Chunks as QR Codes")

and the referred [section](https://smarthealth.cards/#encoding-chunks-as-qr-codes) refers to "Each chunk of the JWS string", singular.

Now, what's the intent here? One QR per JWS, or a QR with concatenated JWS? If the latter, how? Also if the latter, why have a different behavior for files and QRs (another way of asking: do we really need that multi-JWS per card feature?)

(stemming from [issue 61](https://github.com/microsoft/health-cards-validation-SDK/issues/61) of the validation SDK)

**Comment by jmandel** [comment]
The intention right now is:

* multiple health cards (JWSs) can be packaged into a single JSON file
* a singe health card (JWS) can be represented in a QR (or, if it's too big, >1 QR)

We've had some discussion about a presentation format for concatening >1 (small) health card in a single QR, but we haven't decided to do this yet; may do in the future if it becomes important to present multiple cards from disparate issuers in a single flow.

**Comment by jmandel** [comment]
I wouldn't necessarily object to restricting the `.smart-health-card` file to contain a single JWS;  it might be more complexity than it's worth.

**Comment by christianpaquin** [comment]
> I wouldn't necessarily object to restricting the `.smart-health-card` file to contain a single JWS; it might be more complexity than it's worth.

It does introduce some complexity for verifiers, so it depends on the scenarios. There are no restrictions between the JWS, so the "card" could effectively become a "wallet" (is that even allowed, have multiple JWS from different issuers? Spec says yes, right?). On the other hand, @kevin-durand (who opened the issue) has a use case for it, so it's ok if it is useful to deployers.

If we keep this, I suggest adding a few clarifications to the spec, and adding an example. (I can create a PR for these)

**Comment by jmandel** [comment]
Thanks -- worth adding clarifications when you're ready. Will keep this open to track.

**Comment by christianpaquin** [comment]
Will do tomorrow.
