### ISSUE TITLE
Best way to verify .smart-health-card JWS

### ISSUE THREAD

**Issue by gopalp19** [smart-on-fhir/health-cards#133]
My team has been able to map our FHIR resources into the JWS for .smart-health-card files. We want to be able to also test and show that what we built can be decoded later on.

Is there an example or suggestion on how to decode the .smart-health-card files to show what's in it? We used the node-jose package to create the JWS.

**Comment by jmandel** [comment]
The SDK listed at https://smarthealth.cards/#what-testing-tools-are-available-to-validate-smart-health-cards-implementations is a good starting point; it can read QRs and `.smart-health-card` files.

**Comment by gopalp19** [comment]
Ah this is great...should have kept reading to the FAQ's part. Thanks @jmandel !
