### ISSUE TITLE
Guidance on health cards with 2+ immunization records

### ISSUE THREAD

**Issue by gopalp19** [smart-on-fhir/health-cards#135]
We've noticed there are cases where for one person, there may be 2+ immunization records. I'm assuming we would want to send ALL immunization records (related to covid19) as part of the health card. It's then up to the verifier to validate those records to their own needs?

**Comment by jmandel** [comment]
Yes -- are you following the guidance at https://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/ ? Examples (0) and (1) at https://smarthealth.cards/examples also show how this behavior, where a full series of COVID-19 immunizations are conveyed.
