### ISSUE TITLE
De-duping Guidance for Wallets 

### ISSUE THREAD

**Issue by jdkizer9** [smart-on-fhir/health-cards#14]
Is there any concept of a stable unique identifier that wallets can use to de-dupe VCs? If not, is there any guidance for wallets on how to de-dupe VCs. For example, if the contents of the `credentialSubject`/`vc` object are expected to be stable, wallets could canonicalize the json object, then hash and derive an identifier from that.

**Comment by jmandel** [comment]
In general, I think this is content-based. For example, a wallet can inspect the contents of credentials to determine whether the Immunization records in one are fully subsumed by another.

@jdkizer9 I'm going to close this issue if you want to open a separate PR proposing language on this, I'd be happy to review.
