### ISSUE TITLE
patient onboarding -- what's a QR code?

### ISSUE THREAD

**Issue by isaacvetter** [smart-on-fhir/health-cards#143]
In our UX studies with patients there has been a lot of confusion about what a QR code is. (For example, during studies with people who only use a PC and print out thing they need.)
 
The main confusions :
•	Why can't I just show written status (green check mark with text) from the screen?
•	What information am I giving them?
•	Can I use a picture of the QR code instead of having the app on my phone?
 
It would be nice for the on-boarding material to explains what the QR code is and how to use it.

**Comment by jmandel** [comment]
Agreed that more context here is a good idea. In general, our spec-level "onboarding" won't be able to go into the details of platform-specific or app-specific or issuer-specific points, so there's some limit to what we can explain here. I think we have FAQs now around "What information am I giving them?"; is there a general-purpose answer to the "green check mark" question? My sense is that this will be a verifier-specific issue.

Are you able to share more details (here or privately) about your UX testing, and what apps/verifiers/scenarios they involve?

**Comment by aidan-plenert-macdonald** [comment]
I ended up here from looking at https://myvaccinerecord.cdph.ca.gov/

I also don't know what the QR code is/does. When I scan it with a QR code scanner on my phone I get `shc:/1398362592639836....`. It's not clear how to use this.

**Comment by arztnh** [comment]
I had the same problem. Could not import this pass into either
    Excelsior nor VeriFly.  I'll ask CA about this (I work with them).
    
    Noam
    
    On 6/22/2021 12:12 PM, Aidan Macdonald
      wrote:
    
    
      
      I ended up here from looking at https://myvaccinerecord.cdph.ca.gov/
      I also don't know what the QR code is/does. When I scan it with
        a QR code scanner on my phone I get shc:/1398362592639836.....
        It's not clear how to use this.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/smart-on-fhir/health-cards/issues/143#issuecomment-866260193",
"url": "https://github.com/smart-on-fhir/health-cards/issues/143#issuecomment-866260193",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by arztnh** [comment]
But I just was able to import it into the CLEAR app and it worked!
    Wow!
    
    Noam
    
    On 6/22/2021 12:12 PM, Aidan Macdonald
      wrote:
    
    
      
      I ended up here from looking at https://myvaccinerecord.cdph.ca.gov/
      I also don't know what the QR code is/does. When I scan it with
        a QR code scanner on my phone I get shc:/1398362592639836.....
        It's not clear how to use this.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/smart-on-fhir/health-cards/issues/143#issuecomment-866260193",
"url": "https://github.com/smart-on-fhir/health-cards/issues/143#issuecomment-866260193",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jmandel** [comment]
@aidan-plenert-macdonald re: your post above, https://smarthealth.cards has an introduction for end-users including FAQ.
