### ISSUE TITLE
Why infer the publickey from 'iss' claim? What about using the 'jku' header?

### ISSUE THREAD

**Issue by vsmahesh** [smart-on-fhir/health-cards#146]
What was the reason for using the `iss` claim to represent the public key instead of the [`jku` header](https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.2)? 
The verification process involves two actions, at a high level:
1. verify the digital signature of JWS
2. verify the content

Inflating the payload becomes a prerequisite for signature verification, and is an overhead if you look at a single responsibility perspective. If we use the 'jku' header, this computing overhead can be avoided. Also, I feel this will make the spec more aligned with the existing standards.

Any thoughts?

**Comment by jmandel** [comment]
The motivation here is 1) save space by avoiding the need to include two distinct claims, and 2) avoid the need for needing to bind arbitrary JWK URLs to issuers (e.g., if we used an unconstrained `jku`, we'd want some way to prevent malicious actor's from using an valid issuer URL together with a malicious `jku`).

**Comment by vsmahesh** [comment]
Thank you for the reply.

Is there any other function for the `iss` claim? Can we completely avoid it and relay only on the `jku` header?

**Comment by vsmahesh** [comment]
I just realized that 'issuer' is mandatory as per the [verifiable credential specification](https://www.w3.org/TR/vc-data-model/#issuer). So taking the previous question back.

Thanks

**Comment by jmandel** [comment]
Sure thing. Expectation is that the issuers domain is something that participants might recognize or can look up independently (e.g. the public domain for a retail pharmacy chain) as (part of) a basis for trust.
