### ISSUE TITLE
QRCode generation

### ISSUE THREAD

**Issue by christopher-eddy-state-ca-gov** [smart-on-fhir/health-cards#151]
Is there a .netcore package for generating QRCodes that allow for specifying multiple segment modes for different bytes such "bytes" and "numeric"?

**Comment by christianpaquin** [comment]
@angusmillar [announced](https://chat.fhir.org/#narrow/stream/284830-smart.2Fhealth-cards/topic/.2ENET.20Library) today on zulip a .NET library for health cards. The library handles multi-segments (see [this code snippet](https://github.com/angusmillar/SmartHealthCard/blob/master/SmartHealthCard.QRCode/Encoder/QRCodeEncoder.cs#L19)). Not sure if this is his code, or if he uses a 3rd party lib, but take a look!

**Comment by jmandel** [comment]
Under the hood it uses https://www.nuget.org/packages/Net.Codecrete.QrCodeGenerator

I'm adding a wiki page at https://github.com/smart-on-fhir/health-cards/wiki/Libraries-for-SMART-Health-Cards to track recommendations
