### ISSUE TITLE
example-01-d-jws.txt is not a valid JWT and payload is not encrypted

### ISSUE THREAD

**Issue by pradeepBoston** [smart-on-fhir/health-cards#161]
Example files given on Smart Health cards are NOT valid JWT 
https://spec.smarthealth.cards/examples/example-01-d-jws.txt 

Test:
Use jwt.io to verify payload

Payload is NOT encrypted. 
It is raw copy of zlib deflate operation. 

A valid JWT will have payload also encrypted.

[valid_jwt_example.txt](https://github.com/smart-on-fhir/health-cards/files/6811610/valid_jwt_example.txt)

Please clarify no encryption for payload.

**Comment by p2-apple** [comment]
Hey Pradeep, please see Josh's response in #128 . Hope that clears up any ambiguity!

**Comment by pradeepBoston** [comment]
If payload is not encrypted with SHA-256 header "shc:/" is used further in https://spec.smarthealth.cards/examples/example-00-f-qr-code-numeric-value-0.txt ?

**Comment by p2-apple** [comment]
> If payload is not encrypted with SHA-256, why header "shc:/" is used further in https://spec.smarthealth.cards/examples/example-00-f-qr-code-numeric-value-0.txt ?

`shc:/` is a [scheme registered with IANA](https://www.iana.org/assignments/uri-schemes/prov/shc) that we use [for QR code representation](https://spec.smarthealth.cards/#encoding-chunks-as-qr-codes). It's not directly related to our use of JWT or JWS.

**Comment by pradeepBoston** [comment]
raw BLOB data will be used for all types of data exchange or just for QR code ?
