### ISSUE TITLE
Incorrect JWS signature

### ISSUE THREAD

**Issue by pradeepBoston** [smart-on-fhir/health-cards#171]
In "Decode Numeric Encoding" section  https://demo-portals.smarthealth.cards/VerifierPortal.html the  
payload is not in compact JWS format base64url.base64url.base64url

The output and signature of example numeric 
https://spec.smarthealth.cards/examples/example-00-f-qr-code-numeric-value-0.txt 
is also not on base64 JWS payload.  

As per rfc7515  
https://datatracker.ietf.org/doc/html/rfc7515#section-3.3

In the JWS Compact Serialization, a JWS is represented as the
   concatenation:

      BASE64URL(UTF8(JWS Protected Header)) || '.' ||
      BASE64URL(JWS Payload) || '.' ||
      BASE64URL(JWS Signature)

**Comment by jmandel** [comment]
Thanks for submitting an issue here. Can you clarify what specifically you're seeing that's different from what you expect?

**Comment by jmandel** [comment]
Are you just pointing out the fact that the numerical encoding isn't itself a JWS (and rather is a transformed artifact, where each character of the JWS is replaced with a pair of digits)? https://spec.smarthealth.cards/examples/ shows examples of each step in the process, and https://spec.smarthealth.cards/#encoding-chunks-as-qr-codes describes the transformation.

**Comment by pradeepBoston** [comment]
The signature used in example is custom signature of compressed data. It is valid custom signature but not a valid JWS Signature. 
https://datatracker.ietf.org/doc/html/rfc7515#section-5.1

**Comment by lcmaas** [comment]
For a HC, the compressed data is the JWS Payload, and the signature should be computed as per the RFC section you referenced. Take a look at issue #128 for further discussion; hopefully that will clarify.

**Comment by jmandel** [comment]
Agreed @lcmaas -- I'm going to mark this as closed, but please re-open if this is not clear upon review @pradeepBoston
