### ISSUE TITLE
Publish reference implementation of card parser

### ISSUE THREAD

**Issue by fulldecent** [smart-on-fhir/health-cards#181]
Please publish a reference implementation program that can parse `shc` such as the one published at https://smarthealth.cards on the top of the page on the picture.

**Comment by jmandel** [comment]
You may be interested in the links at https://spec.smarthealth.cards/#what-testing-tools-are-available-to-validate-smart-health-cards-implementations, which includes links to open source tools that generate and parse SMART Health Cards

**Comment by fulldecent** [comment]
Great, thank you
