### ISSUE TITLE
Error related to generationg certificates

### ISSUE THREAD

**Issue by EvgenMatiola99** [smart-on-fhir/health-cards#191]
Hi, I am a bit confused to generate certificates by command `npm run generate-keys`
I am getting the next error: Invalid EC P-256 ASN.1 private key header

Thanks for your advices

**Comment by jmandel** [comment]
You should be able to 

```sh
git clone ttps://github.com/smart-on-fhir/health-cards
cd health-cards/generate-examples
npm ci
 ./generate-cert-chain.sh
npm run generate-keys
```

... but can you clarify what you're aiming to accomplish with this? The example generator is mainly intended to support https://spec.smarthealth.cards/examples/ and not intended for broader use.

**Comment by EvgenMatiola99** [comment]
Now it is working
Thanks @jmandel

**Comment by EvgenMatiola99** [comment]
I am trying to generate keys and provide them to my smart-health-card

**Comment by jmandel** [comment]
OK -- I'd recommend checking in at https://chat.fhir.org/#narrow/stream/284830-smart.2Fhealth-cards to talk through your use case; you probably don't want to be using the code in this repo for any purpose other than learning or contributing to the core spec.
