### ISSUE TITLE
Golang "swiss army knife" for smart health cards

### ISSUE THREAD

**Issue by amitkgupta** [smart-on-fhir/health-cards#211]
Hi there,

I wrote some libraries that can be composed together to generate smart health card QR codes for COVID-19 immunizations. The code is in Golang, and might be a nice addition to the .NET and Ruby repos listed [here](https://github.com/smart-on-fhir/health-cards/wiki/Libraries-for-SMART-Health-Cards#what-are-good-libraries-for-working-with-smart-health-cards).

My repo is here: https://github.com/amitkgupta/go-smarthealthcards

If you like it, please consider adding it to your wiki! I wasn't able to find Go-based solutions in this wiki or elsewhere on the web, so I wrote one myself and I hope it can be of use to others!

**Comment by jmandel** [comment]
Thanks! Added to https://github.com/smart-on-fhir/health-cards/wiki/Libraries-for-SMART-Health-Cards (BTW the wiki should be open for editing if you need to add any context.)

**Comment by amitkgupta** [comment]
Awesome, thanks!
