### ISSUE TITLE
Can I get clarification on the section "Every Health Card can be embedded in a QR code"

### ISSUE THREAD

**Issue by zachary822** [smart-on-fhir/health-cards#216]
Specifically what it means by "Does not capture a digital record of a request for presentation" and "Does not capture a digital record of the presentation". Does it mean that the QR codes have to be generated *de novo* every time, and it may not be sent along with things such as pdf reports or emails, that have the potential to be stored long term?

**Comment by jmandel** [comment]
In our current spec, QR codes are static bearer tokens; they represent a verifiable credential, and not a verifiable "presentation" of that credential (which we offered as a feature in our pre-release draft specs).

That language just means that after a SMART Health Card presentation is over, there's no explicit  signed assertion stating things like:

* So and so requested the presentation of a SMART Health Card
* So and so responded by presenting one

This is pretty obvious in cases where SMART Health Cards are generally used, and it's not actually worth calling out in our spec today; it's mainly a historical artifact.
