### ISSUE TITLE
Response code 404 (Not Found)

### ISSUE THREAD

**Issue by yarodevuci** [smart-on-fhir/health-cards#234]
TTPError: Response code 404 (Not Found)
    at Request.<anonymous> (health-cards-main/generate-examples/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Does anyone had same issue?

**Comment by christianpaquin** [comment]
Did you get this by running `npm run generate-examples`? Looks like the retrieved URLs need to be updated. Thanks for the report.

**Comment by christianpaquin** [comment]
The files `Scenario1Bundle.json` and `Scenario2Bundle.json` are no longer in `https://github.com/HL7/fhir-shc-vaccination-ig/tree/master/examples`. Looks like they were moved by recent PRs, @masnick, but I'm not sure where.

**Comment by jmandel** [comment]
Indeed, https://github.com/HL7/fhir-shc-vaccination-ig/blob/master/examples/README.md and https://github.com/HL7/fhir-shc-vaccination-ig/blob/master/script/validate-examples still refers to these files. Would be good to bring them back :-)

**Comment by masnick** [comment]
Apologies, I did not realize this depended on the location of those examples.

We are in the process of moving the examples to inside the IG as part of ballot reconciliation. The new examples are at:

1. "Scenario 1": https://github.com/HL7/fhir-shc-vaccination-ig/blob/master/input/examples/bundle-immunization-covid.json
2. "Scenario 2": https://github.com/HL7/fhir-shc-vaccination-ig/blob/master/input/examples/bundle-immunization-monkeypox.json
3. "Scenario 3": https://github.com/HL7/fhir-shc-vaccination-ig/blob/master/input/examples/bundle-lab-test-results-covid.json

We still have a GitHub Action to auto-generate full SMART Health Cards from these examples, but the output of the script has moved into its own orphan branch to avoid a messy history on `master`: https://github.com/HL7/fhir-shc-vaccination-ig/tree/master-examples

**Comment by christianpaquin** [comment]
Looks like the "scenario 1" file is different than what is in the current spec (3 doses vs 2). Our example 2 used a modification of the "scenario 1" file, but not one of these new examples.  Looks like we have two choices: 1) archive our old example files as fixtures vs. external downloads and keep the spec as is, or 2) update the spec examples to map to the updated external Scenario 1 file.

**Comment by jmandel** [comment]
Agreed with the analysis! I think a good compromise might be:

1. snapshot + internal copy the examples we care about, for our embedded examples 
2. link out to the IG for more detail/ other examples

**Comment by yarodevuci** [comment]
@jmandel @christianpaquin thanks for assistance. Is there a temp walkarounds ?

**Comment by jmandel** [comment]
@yarodevuci can you confirm what commands you're running and what you're trying to accomplish? (Will try to get a fix in place ASAP so no workaround is needed, in any case...)

**Comment by jmandel** [comment]
See fix in https://github.com/smart-on-fhir/health-cards/pull/236 (you can use this branch for now; we'll merge ASAP).

**Comment by christianpaquin** [comment]
Oh, didn't notice your PR @jmandel; I just created #237. I see you are using @masnick new example file with 3 doses for the spec example 00 and 01. We can certainly do this (better ongoing alignment). I've archived the old examples in the PR I just pushed.

**Comment by yarodevuci** [comment]
@jmandel running `npm run generate-examples ` and trying to build examples.

**Comment by jmandel** [comment]
Thanks! You should be good to go now.

**Comment by yarodevuci** [comment]
yes the issue was in https://raw.githubusercontent.com/HL7/fhir-shc-vaccination-ig/master/examples/Scenario2Bundle.json that resulted a 404.
Thanks for the fix.
