### ISSUE TITLE
client_uri should be a property on SIOP Request, not .registration

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/health-cards#24]
`client_uri` should be not in `registration` but an optional parameter directly in the request? 

![image](https://user-images.githubusercontent.com/313089/104254544-af415f00-543c-11eb-9e18-035bfc1e38a6.png)

`client_uri` should move up to be a sibling

**Comment by madaster97** [comment]
Having trouble accessing the [Openid Spec](https://openid.net/specs/openid-connect-registration-1_0.html) for Dynamic client registration, but the [OAuth RFC](https://tools.ietf.org/html/rfc7591#section-2) I think it's based on has "client_uri" in the metadata.

**Comment by p2-apple** [comment]
> Having trouble accessing the [Openid Spec](https://openid.net/specs/openid-connect-registration-1_0.html) for Dynamic client registration, but the [OAuth RFC](https://tools.ietf.org/html/rfc7591#section-2) I think it's based on has "client_uri" in the metadata.

Yes, just like e.g. `scope` and `responseType`, so I think this move makes sense.

**Comment by jmandel** [comment]
Uh, now that I got around to implementing this, I'm not so sure it's correct :-)

I'll follow up.

**Comment by madaster97** [comment]
@p2-apple `scope` and `responseType` are not part of the [Metadata definition](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata). That's why they aren't in the registration object.

Those two fields are specific to a given **request**, and not generically to a given client. Note, `response_types` is part of the metadata definition, and on any given request the `responseType` chosen should be present in that array.

**Comment by jmandel** [comment]
Agreed @madaster97. I'm double checking with the person who initially raised this issue to make sure I'm not missing anything, but my reading matches yours.

**Comment by p2-apple** [comment]
I was comparing it with the OAuth2 metadata keys, but right, client_uri has a different meaning there. From an OID perspective it actually seems to make sense to keep it in registration, thanks for the close reading @madaster97 !

**Comment by jmandel** [comment]
Thanks -- I've reverted the fix and will close this out.
