### ISSUE TITLE
show endorsements

### ISSUE THREAD

**Issue by fulldecent** [smart-on-fhir/health-cards#27]
Apparently, Microsoft, Salesforce, and Oracle have endorsed this project as per:

https://www.theverge.com/2021/1/14/22231187/microsoft-salesforce-oracle-digital-vaccination-records

This is an important fact that should be disclosed in README.

**Comment by rdwatters** [comment]
Indeed. Stay ahead of the crackpots.

**Comment by jmandel** [comment]
Great suggestion. I've added a link to VCI in https://github.com/smart-on-fhir/health-cards/commit/d0619a82fca8ede11de1cddca25e85cd40091c2f. (Given that the organizations listed above are participating through VCI, I think it's easier to manage this list through a level of indirection.)
