### ISSUE TITLE
Typos & Clarifications

### ISSUE THREAD

**Issue by madaster97** [smart-on-fhir/health-cards#29]
# Overview
Reading through the docs I've run into a couple places where we could be clearer.

# List
- [x] Health Wallet as [Issuer](https://healthwallet.cards/#install-a-health-wallet-app): In linked section, we say the wallet needs to generate a key *to enable verification of JWT signatures created by **this issuer***. Could we clarify that **issuer is referring to the holder signing JWS**, not an actual *Issuer* from the [conceptual model](https://healthwallet.cards/#conceptual-model)?
- [x] Clarify [SIOP Request Payload iss DID](https://healthwallet.cards/#connect-health-wallet-to-lab-account): In the example **DID SIOP Request**, the JOSE header has a `kid` of `did:ion:<<identifer for lab>>#<<verification-key-id>>`, and the payload has an `iss` claim of `did:ion:<<did-value>>`. Should the iss actually be `did:ion:<<identifer for lab>>` for clarity, since this JWT was issued by the lab?
- [x] Clarity the phrase *"as JWE or JWS"* ([example](https://healthwallet.cards/#lab-results-are-finalized) as VCs), in that this is decided by the presence of `id_token_encrypted_response_*` parameters in the SIOP request.
- [ ] TBD - Interactions between verifier and issuer. Do verifiers call an issuer's well-known did config?

**Comment by jmandel** [comment]
Thanks for these! Can you review https://github.com/smart-on-fhir/health-cards/pull/38 to ensure I've covered (1-3) correctly? And re: (4) this is a broader topic that needs more explicit language in the spec; would you mind capturing this in a separate issue?

**Comment by madaster97** [comment]
Hey Josh,

1 and 2 look good! But I'm realizing I had 3 wrong.

The `id_token_encrypted_response_*` value is presented by the RP (lab/issuer) and used by the SIOP (holder) to encrypt the **SIOP response**, and not used by the issuer to encrypt VCs.

The way that VCs get encrypted is not well-defined. During a SIOP flow, an issuer just sort of _notices_ that a holder has encryption key(s), and chooses to use one at it's own discretion. I think that sort of explanation should replace what you have in the VCs section.

I don't think we should say too much on the topic, other than mentioning that RPs can choose to not trust a given holder if it doesn't own/present an encryption key. In the `$HealthConnect` workflow, this is managed using the `encryptForKeyId` parameter, but could also optionally be enforced by an issuer by just choosing any key the wallet has.

**Comment by jmandel** [comment]
You're correct -- choice to encrypt a VC in a `.fhir-backed-vc` file is up to the issuer, though of course it can be *informed by* preferences expressed by the wallet *if* there is a connected wallet. (There are use cases where the user doesn't have encryption keys or eve a DID, and issuers can still create `.fhir-backed-vc` files. I'll update the PR to reflect these considerations.

**Comment by jmandel** [comment]
Thanks again for your help with this @madaster97
