### ISSUE TITLE
Trust over IP Layers as a development model

### ISSUE THREAD

**Issue by cjbuchanan** [smart-on-fhir/health-cards#35]
# The Trust over IP Stack

Just wanted to start a discussion on the Trust over IP Stack.  The stack outlines the required components for the trust ecosystem in the context of decentralized identity technologies like DID and VCs and represents a comprehensive view informed by those who have developed the underlying standards and technologies as well as companies that have been developing solutions in this space from its inception.

Here is the stack:
![ext-img](https://github.com/trustoverip/SC/blob/master/presentations/stack-diagrams/images/Trust%20over%20IP%20Stack%20-%20Diagrams.010.png?raw=true)

As you can see each layer of the stack has both technical and governance components.  In my short exposure to VCI, it appears we are primarily focused on Layer 3, and reducing governance requirements is a design goal/necessity.  However, you cannot wish away governance.  You can encode it or externalize it, but those choices should be made and justified by the project so that implementers are aware of those choices and a coherent implementation remains possible across multiple providers.

I would propose an ecosystem subgroup to help quickly identify and document the relevant questions at each layer for both technical and governance so that we can incorporate that into the project design documents and ensure a coherent effort across all partners.

# The Trust over IP Foundation
The [Trust over IP Foundation](https://trustoverip.org) is part of the [Linux Foundation](https://www.linuxfoundation.org) and was created to address the need for some sense of orthodoxy in integrating all of the disparate technologies supporting efforts like VCI.  Trust over IP is tech agnostic and neither prescribes a specific solution nor seeks to compete with standards or providers, but instead informs and advises solution developers (like VCI) in wading through all the design options.  [MITRE](https://www.mitre.org) is a steering committee member for Trust over IP and I am MITRE's representative to the foundation.  Feel free to reach out.

Here is some additional information on the Trust over IP Foundation and its purpose:
- [Introductory Whitepaper](https://trustoverip.org/wp-content/uploads/sites/98/2020/05/toip_introduction_050520.pdf)

**Comment by cjbuchanan** [comment]
I forgot to mention... Trust over IP is tech agnostic and does not prescribe specific solutions.

**Comment by jmandel** [comment]
Capturing notes from phone call:

* We agreed to add a page to the spec providing a "Trust Over IP Mapping" -- much the way that FHIR provides [RIM and v2 mappings](http://build.fhir.org/medicationrequest-mappings.html) for its resources. The idea is if you're familiar with ToIP and speak that language, you can read the mapping as a primer to understand how SMART Health Cards fits into this world view
* We recognized there's a slight risk that the mappings may get out of sync with reality, so we need to make sure folks who deeply understand both sides of the mapping can review for accuracy.

**Comment by cjbuchanan** [comment]
Decided.. mapping under issue #59.
