### ISSUE TITLE
Handling the delegation of issuing credentials

### ISSUE THREAD

**Issue by davebryson** [smart-on-fhir/health-cards#40]
What if an issuer such as Acme hospital wants to delegate the issuance of credentials to labs or physician within the organization? 

While Acme may be recognized as a trusted issuer, delegates may not.  This will likely require some form of provenance chain `Acme - delegates -> lab - delegates -> physician` that will need to be followed in order to verify the integrity of a given credential.  [Aries](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0103-indirect-identity-control) has some information on this, but I'm not sure the problem is actually solved yet.

**Comment by jmandel** [comment]
Agreed -- there are useful and interesting delegation capabilities can be help in establishing a chain of trust.

For "v1", we're planning to leave these details out of scope. In other words, for our initial release: Acme can have an internal delegation structure, but needs to either 1) "own" the signatures at the organizational level, or 2) ensure that all "issuer-level" DIDs within its own hierarchy can be directly known/trusted by relying parties.

(This kind of detail should eventually be captured by "trust frameworks" and published as "allow lists" of issuers; such capabilities are independent of the core issuance/validation workflow can get more sophisticated over time, so I'm comfortable starting fairly naively.)
