### ISSUE TITLE
Lab Results vs Immunization Status

### ISSUE THREAD

**Issue by arztnh** [smart-on-fhir/health-cards#51]
Note that the Framework document references a "lab" which seems to cover the COIVID testing use case but not the immunization use case. Perhaps these two user experiences should be separated as they are not exactly the same nor used necessarily in the same way at the same time. This is also not consistent with the primary use case identified in the draft FHIR IG.

**Comment by jmandel** [comment]
Thanks -- and indeed, a lot of the language refers to labs for purely historical reasons. We need clean this up.
