### ISSUE TITLE
Immunization Forecast

### ISSUE THREAD

**Issue by arztnh** [smart-on-fhir/health-cards#52]
As best as I can tell (and I am no FHIR expert) the current draft IG has no provision for a bundle that includes immunization forecast as a component. For purposes of completeness this should be included. It does not mean that any  particular use case needs to use it but these FHIR resources should be available.  This data is contained in the ImmunizationEvaluation and ImmunizationRecommendation resources. Work on this topic is conducted within HL7's Public Health WG. Key people working on this include Nathan  Bunker <nbunker@immregistries.org> who has been participating in the weekly Tech WG calls, Eric Larson  <elarson@immregistries.org>, Craig Newman  <Craig.Newman@altarum.org>, and Daryl Chertcoff <daryl@hln.com> who works for me.

**Comment by arztnh** [comment]
Sorry, is there a way to move an issue there? Should I post a new issue there?

**Comment by jmandel** [comment]
My apologies -- GitHub does have a "move issue" feature but it won't work across orgs. I'll close this one (sorry for the hassle :/))
