### ISSUE TITLE
Source of truth for immunization records?

### ISSUE THREAD

**Issue by arztnh** [smart-on-fhir/health-cards#53]
I am not sure if this is in scope for this project, but the notion of "source of truth" for immunization records is an open issue. Is it the EHR? IIS? Both? Either? Note that for both the EHR and IIS that records can change and be corrected for many reasons: simple errors, discovery of a bad vaccine lot invalidating the efficacy of the dose administered. Should  the patient be able to capture their immunization record and store it in their digital wallet and assume it is forever "true"? Should they be made to validate that record from its source?

A secondary issue involves IIS or other points of record consolidation (potentially an HIE). They are only as good as the systems that submit data to them (primarily EHRs) but also apply some quality assurance steps to consolidate a coherent record for a patient. Should they be a preferred, more centralized source of information over an EHR?

Does this project even care about these distinctions?

**Comment by jmandel** [comment]
Thanks @arztnh for these questions. The quick answer is it'd be great if you can raise this issue in the "COVID-19 Data Profile IG" at https://github.com/dvci/vaccine-credential-ig/issues (GitHub won't allow me to move the issue directly).

Thinking from the Covid-19 data profile perspective, we want to allow for some flexibility in modeling these details:

* Issuers are in charge of deciding whether and when to *expire* a credential, by optionally setting an `exp` value. We recommend against this in general, but in some circumstances this may be prudent. A verifying party can check to see whether a credential is past its expiration date when validating the credential.
* Regarding sources of truth, we use the FHIR https://hl7.org/fhir/R4/immunization-definitions.html#Immunization.primarySource flag to indicate whether information has been recorded from a primary source. Again, this information is captured in a credential but it's up to a verifier (or: the algorithm a verifier chooses to apply) to decide whether to "discount" its trust in data based on this flag.

So: this project very much cares about the distinctions you raise, and we want to make sure they can be communicated clearly. But we don't set the rules on how much they matter to verifiers,
