### ISSUE TITLE
Should the SIOP Request Object from Verifier to Holder contains Verifier's DID, instead of Issuer's DID?

### ISSUE THREAD

**Issue by zhj5825** [smart-on-fhir/health-cards#57]
### Presentation Protocol Details

The process begins with a QR code or `openid://` link. The only differences are:

1. The SIOP Request Object includes a `claims` object asking for relevant Verifiable Credentials to be included in the response:

    ```json
    {
      "iss": "did:ion:<<identifier for issuer>>",     # should this be Verifier's DID instead?
      "response_type": "id_token",                       # should the response_type still be an id_token, when what Verifier cares about is Holder's VC?
      "client_id": "<<URL where response object will be posted>>",
      "scope": "openid did_authn",
      "response_mode" : "form_post",
      "response_context": "wallet",
      "nonce": "<<unique value>>",
      "state": "<<client-supplied value, possibly empty>>",
      "registration":  {
        "id_token_signed_response_alg" : "ES256",
        "id_token_encrypted_response_alg": "ECDH-ES",
        "id_token_encrypted_response_enc": "A256GCM",
        "client_uri": "<<base URL for issuer>>"
      },
      "claims": {
        "id_token": {
          "https://smarthealth.cards#covid19": {"essential": true},
        }
      }
    }
    ```

**Comment by jmandel** [comment]
Thanks for this!

> # should this be Verifier's DID instead?
This was a copy/paste error introduced yesterday; fixed now.


>  # should the response_type still be an id_token, when what Verifier cares about is Holder's VC?
Yes, this instance of the DID-SIOP protocol results in a Verifiable Presentation (expressed in the form of an `id_token`, which is a JWS signed by the holder, following the OpenId Connect specification). Inside this VP is one ore more VCs (themselves also JWS structures, signed by issuers).
