### ISSUE TITLE
Document paper-based (non-verifiable) presentation of verifiable credentials

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/health-cards#6]

**Comment by radamson** [comment]
Would it be possible to still have a paper-based _verifiable_ presentation of a VC through using QR codes, or some similar technology?

Taking the example [VC.json](https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/master/src/fixtures/vc.json), minifying/compacting it, and then base64 encoding it resulted in a 3206 character code which meets the 4296 alphanumeric character limit for a QR code. Printing and carrying a 177x177 QR code might be a little extreme, especially if minimal error correction is employed to accommodate the high character limit, and real credential subject payloads may be larger than can fit anyways. Smarter encoding or using the QR code mode might provide some more headroom. In cases where a trusted intermediary evaluates the business rules and health data to issue yes/no decision VC this approach could be more palatable.

Alternatively, I could envision a QR code that encodes a URL which could be dereferenced to a VC, but this would pose clear privacy challenges if that URL was openly accessible. If it was secured by a trusted party and only accessible via some authentication and authorization process it might alleviate some of the concerns, but it adds a lot of complexity.

These ideas might be a stretch too far, or maybe outright nonsensical, but food for thought at least!

**Comment by jmandel** [comment]
A *verifiable* presentation as we usually talk about it requires some key material to sign the presentation, and requires a "challenge" (e.g., in the form of a nonce provided by the verifier, which the holder includes in the presentation to prove it's being done specifically for this verifier). So if we're talking about *paper-based* QR codes, no there's not a good flow for this.

(But if you're talking about QR codes generated/displayed/scanned dynamically from a phone, this is definitely possible but out of scope for this issue #6 because it requires a smartphone. A few notes on this, though:

 1) if you have a smartphone at presentation time, the easier recommendation is just to use the DID-SIOP presentation flow, where the verifier displays a QR code to kick things off, and the holder posts a Verifiable Presentation to a verifier-specified URL, which all works fine if parties are online,

2) we've seen examples of folks playing with serial presentation of QR codes, which is cute but to me feels like an error-prone UX,

3) if you provide a URL that dereferences to a VC, you have the privacy challenge you noted here, and also it requires the verifier at least to be online, which nudges us back toward DID-SIOP territory. I actually think your notion about "some authentication process" isn't a bad one -- like, I wouldn't want to *standardize* this, but presenting a QR code that requires an extra one-time passphrase or whatever might be pretty practical.

All this said, it'd be good if we discuss presentation techniques/trade-offs in the context of specific constraints and assumptions. So maybe we end up with a few kinds of presentation guidance depending on the circumstances. My hope is to _standardize_ just one of these to start, and leave the others 'til later.)

**Comment by radamson** [comment]
I appreciate the explanation and that makes this a lot clearer to me (I think). I missed the key distinction here between a _verifiable presentation_ and a _verifiable credential_. The verifiable credential data could be put on a piece of paper and still be verifiable, but the presentation itself cannot be verified because, as you noted, there isn't a challenge specific to this request from the verifier. There is no way to ensure that this piece of paper was generated for this specific request.

I'm also realizing that these approaches are touched upon already in the [Fallback for users without a smartphone](https://healthwallet.cards/#potential-extensions) section...oops!

**Comment by jmandel** [comment]
Sure thing! I'm closing this in favor of the discussion at https://github.com/smart-on-fhir/health-cards/discussions/33 (will cross-link).
