### ISSUE TITLE
Define a way to pass {{uuid::FHIR REST URL}} maps in $HealthWallet.issueVc

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/health-cards#7]
The goal here is to:

* Allow a mobile wallet to tell which source FHIR resources (on a FHIR server) have formed the basis for the resources bundled into a Health Card
* Prevent verifying parties from knowing this information (i..e, it can't be embedded *in* the Health Card)

**Comment by jmandel** [comment]
Maybe next to the VC params, some maps?


```json
{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "verifiableCredential",
      "valueAttachment": {
        "data": "<<base64 encoded VC JWS or JWE>>"
      }
    },
    {
      "name": "resourceLink",
      "part": [
        {
          "name": "uuid",
          "valueUri": "urn:uuid:4fe4f8d4-9b6e-4780-8ea5-6b5791230c85"
        },
        {
          "name": "self",
          "valueUri": "https://lab.example.org/DiagnosticReport/123"
        }
      ]
    },
    {
      "name": "resourceLink",
      "part": [
        {
          "name": "uuid",
          "valueUri": "urn:uuid:911791c4-5131-44ba-85bd-8e6bdf652fd4"
        },
        {
          "name": "self",
          "valueUri": "https://lab.example.org/Observation/456"
        }
      ]
    }
  ]
}
```

**Comment by jmandel** [comment]
@p2-apple we've let this sit for a while; is this feature still useful/important to you? How strongly would you want to see it in v1?

**Comment by p2-apple** [comment]
I forgot about this! I think it would be a nice but completely optional addition. Shall we just define it for v1 so issuers can implement to their choosing? What you suggest seems sufficient and actually nice to me.
