### ISSUE TITLE
Add laboratory credential type to documentation

### ISSUE THREAD

**Issue by nkarip** [smart-on-fhir/health-cards#75]
Add a verifiable credential type to the vocabulary documentation to be used for health cards to convey laboratory data (ie https://smarthealth.cards#laboratory).

**Comment by jmandel** [comment]
@nkarip  is https://github.com/smart-on-fhir/health-cards/pull/76 what you have in mind?

**Comment by nkarip** [comment]
https://smarthealth.cards#laboratory, same pattern as with immunizations - #health-card + #covid19 + #laboratory would indicate a request to issue a VC with SARS-CoV2 labs (no immunizations). We don't have this API pattern documented in the IG itself, wondering if this is the best place to do that.

**Comment by jmandel** [comment]
So I think you're saying "Yes to #76" *and* also maybe describe use of these types in the FHIR IG?

**Comment by nkarip** [comment]
#76 looks good. We can generally state in the IG that it is meant to represent subject for credentials of type #covid19 + (#laboratory +/- #immunization). We can't go into detail about where it might fit into the health cards spec (HL7 balloting restrictions) but I think documenting the relationship should be sufficient for implementers to connect the dots. I can drop a separate issue in the IG for it.

**Comment by jmandel** [comment]
Thanks! I'm merging #76 and closing this, then.
