### ISSUE TITLE
Clarify data type for parameter _since

### ISSUE THREAD

**Issue by yunwwang** [smart-on-fhir/health-cards#82]
"By default, the issuer will return health cards of any age. If the Health Wallet wants to request only cards pertaining to data since a specific point in time, it can provide a _since parameter with a valueDateTime (**which is an ISO8601 string at the level of a year, month, day, or specific time of day**)."

The ISO8601 extended time format (eg: yyyy-MM-ddThh:mm:ss) aligns with FHIR dateTime format.
The ISO8601 basic time format (eg: yyyy-MM-ddThhmmss) does not.
Please clarify if which format does the parameter use?

**Comment by jmandel** [comment]
Sure -- it's a FHIR valueDateTime, so it has to be a valid FHIR DateTime. I'll add a link to the FHIR datatype definition and and an example.
