### ISSUE TITLE
Please clarify usage of resourceLink parameter

### ISSUE THREAD

**Issue by yunwwang** [smart-on-fhir/health-cards#83]
"In the response, an optional repeating resourceLink parameter can capture the link between hosted FHIR resources and their derived representations within the verifiable credential's .credentialSubject.fhirBundle, allowing the health wallet to explictily understand these correspondences between bundledResource and hostedResource, without baking details about the hosted endpoint into the signed credential"

Please clarify if the `resoruceLink` parameter may (or may not) include only part of all resources in the bundle. For example, the bundle have 10 Immunization instance and the `resourceLink` has only 5 of them.

**Comment by jmandel** [comment]
Thanks for this question! Will clarify that there can be 0 or more `resourceLink` response parameters, covering any subset of resources that the server wants to cover.
