### ISSUE TITLE
in issue-vc response, resourceLink may not be unique across >1 VC

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/health-cards#88]
We could say:

## Option 1 -- use param order
Alternate VCs and the resourceLink values associated with the vc

i.e.

> param: VC1, (Resoure Link for VC1)*, VC2, (Resource Link for VC2)*

downside: it's fragile to depend on order

## Option 2 -- add a property into the Resource Link structure
Or we could add a VC index in the Resource Link structure (making it {vc index, bundledResource, hostedResource)

downside: this also has a dependency on order...

## Option 3 -- re-work the verifiableCredential param
Update verifiableCredential to include two parts: vc and resourceLink

downside: this breaks clients that have a simple way to extract VCs today)

## Other options?

**Comment by lcmaas** [comment]
Of the above, I favor Opt2: index 0..1 unsignedInt, if absent the link applies to all returned vcs.

Alternative: Add a VC id (jti). downside: bytes are at a premium due to QR limits. upside: order-independent referencing, facilitate future revocability for errors or fraud.

**Comment by jmandel** [comment]
I'll try a write-up for Option 2 in a PR.

**Comment by p2-apple** [comment]
Option 3 would be good if `resourceLink` was something often present. I expect few endpoints to (be able to) implement it so I'm also leaning to Option 2.

**Comment by yunwwang** [comment]
Maybe a stupid question. Why the response contains multiple VCs? According to the example here: https://smarthealth.cards/#issuer-generates-results, one VC contains full bundle payload. Is that one VC for Immunization, another VC for Observation, etc

**Comment by jmandel** [comment]
As on example: you might have an app requesting a pile of Immunization health cards -- each VC represents a self-contained set of clinical data, so you might get a Heath Cards with COVID-19 immunizations, another with TDAP immunizations, etc. It's best to keep these cards narrowly scoped so users can share them discretely.
