### ISSUE TITLE
Remove encryption key from the issuer public key set

### ISSUE THREAD

**Issue by christianpaquin** [smart-on-fhir/health-cards#93]
The issuer key set published at `https://smarthealth.cards/examples/issuer/.well-known/jwks.json` contains an encryption key. I suggest removing it, since it is no longer used in the spec. The [validation tool](https://github.com/microsoft/health-cards-validation-SDK) shows warning for non-signature keys in the JWKS, so that would reduce the output for the example files.

**Comment by jmandel** [comment]
That's a good point. (I kind of don't mind having it in here because it forces clients to deal the case that only certain keys are `sig` keys -- but that's kind of an accidental value and post-hoc justification ;-) I'll strip it.)
